name: Publish

on:
  push:
    tags:
      - "*"
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: cogna-dev/moonbit-actions/setup@v0

      - name: Publish to mooncakes
        uses: cogna-dev/moonbit-actions/publish@v0.1.2
        with:
          token: ${{ secrets.MOONCAKES_TOKEN }}
